name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: checkout/setup-node@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Fetch repos
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node -p "const repos = $(gh api /users/Juhan280/repos); JSON.stringify(repos.filter(x => ! x.fork && ! x.private && ! ['Juhan280', 'Juhan280.github.io'].includes(x.name)).map(x => ({name: x.name, url: x.html_url,  homepage: x.homepage})))" > dist/gh-repos.json

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist/'

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
